version: 2

jobs:
  credential:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
          name: Creating AWS credentials file
          working_directory: /
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config

  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade

  deploy:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Deploying
          command: eb deploy

workflows:
  version: 2
  build:
    jobs:
      - credential
      - setup
      - deploy:
          requires:
            - credential
            - setup
          filters:
            branches:
              only:
                - master
