version: 2

jobs:
  deploy_prod:
    docker:
      - image: ubuntu
    working_directory: ~/app
    steps:
      - run:
          name: Creating AWS credentials file
          working_directory: /
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            apt-get -y -qq update
            apt-get install python-pip python-dev build-essential
            pip install --upgrade setuptools
            pip install awsebcli --upgrade
      - run:
          name: Deploying
          command: eb deploy

workflows:
  version: 2
  build:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only:
                - master
